package com.diabloid;

enum WeaponType {
    MAGIC_BOLT, TRIPLE_CAST, PULSE_RING, PIERCE_LANCE, DAMAGE_AURA, CHAIN_LIGHTNING, SAW_BLADE,
    FROST_NOVA, TOXIC_DART, FLAME_ORB,
    FIRE_WAVE, FIRE_LANCE, FIRE_METEOR,
    ICE_SHARD, ICE_SPIKE, ICE_STORM,
    WATER_JET, WATER_ORB, WATER_TIDE,
    EARTH_SPIKE, EARTH_QUAKE, EARTH_BLADE,
    THUNDER_SPEAR, THUNDER_FIELD, SHADOW_SCYTHE
}
